kind: pipeline
type: docker
name: default

pipeline:
  compile:
    image: golang
    commands:
      - go build
  test:
    image: golang
    commands:
      - go build
  build:
    image: docker
    commands:
      - docker build -t some/container .
    volume:
      - /var/run/docker.sock:/var/run/docker.sock
  deploy:
    image: docker/compose
    commands:
      - docker compose up -d
    volume:
      - /var/run/docker.sock:/var/run/docker.sock