kind: pipeline
type: docker
name: LL-dronetest

steps:
  - name: check for file changes
    image: herbysk/drone-plugin-check-changes
    settings:
      ignore: [ "/**", "!/.drone.yml", "!/*.go" ]
      negative: .skip
  - name: test compile the go source
    image: golang:alpine
    commands:
      - if [ -f .skip ]; then exit; fi
      - go build
  - name: build a docker image
    image: docker
    commands:
      - if [ -f .skip ]; then exit; fi
      - docker build -t dronetest/goapp .
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock
  - name: deploy a docker container with a docker-compose
    image: docker/compose
    commands:
      - if [ -f .skip ]; then exit; fi
      - docker-compose up -d
    volumes:
      - name: docker_socket
        path: /var/run/docker.sock

volumes:
  - name: docker_socket
    host:
      path: /var/run/docker.sock