kind: pipeline
type: docker
name: built-cli
steps:
  - name: check
    image: herbysk/drone-plugin-check-changes
    settings:
      ignore: [ "/**", "!/.drone.yml", "!/*.go" ]
      negative: .skip
  - name: compile
    image: golang:alpine
    commands:
      - if [ -f .skip ]; then exit; fi
      - go build
#  - name: build
#    image: docker
#    privileged: true
#    commands:
#      - if [ -f .skip ]; then exit; fi
#      - docker build -t dronetest/goapp .
#    volume:
#      - /var/run/docker.sock:/var/run/docker.sock
  - name: deploy
    image: docker/compose
    privileged: true
    environment:
      DOCKER_HOST: "unix:///var/run/docker.sock"
    commands:
      - export DOCKER_HOST="unix:///var/run/docker.sock"
      - if [ -f .skip ]; then exit; fi
      - docker-compose up -d
    volume:
      - /var/run/docker.sock:/var/run/docker.sock